// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggpnghedqaevrujdbhlk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdncG5naGVkcWFldnJ1amRiaGxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NDk4OTksImV4cCI6MjA3MjEyNTg5OX0.mbWoK-_5VI_YSmawIiXtoAznlwKhL5ygEsMZzPb4Upc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});